# Generated by Django 6.0.6 on 2026-06-19 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cittadino',
            fields=[
                ('CSSN', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('dataNascita', models.DateField()),
                ('luogoNascita', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ospedale',
            fields=[
                ('codOspedale', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('citta', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=255)),
                ('dirSanitario', models.CharField(max_length=16)),
                ('latitudine', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitudine', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('codPatologia', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('livello_rischio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PatologiaCronica',
            fields=[
                ('patologia', models.OneToOneField(db_column='codPatologia', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ricoveri.patologia')),
            ],
        ),
        migrations.CreateModel(
            name='PatologiaMortale',
            fields=[
                ('patologia', models.OneToOneField(db_column='codPatologia', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ricoveri.patologia')),
            ],
        ),
        migrations.CreateModel(
            name='Ricovero',
            fields=[
                ('codRicovero', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('durata', models.DecimalField(decimal_places=2, max_digits=8)),
                ('diagnosi', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cittadino', models.ForeignKey(db_column='CSSN', on_delete=django.db.models.deletion.CASCADE, to='ricoveri.cittadino')),
                ('ospedale', models.ForeignKey(db_column='codOspedale', on_delete=django.db.models.deletion.CASCADE, to='ricoveri.ospedale')),
            ],
        ),
        migrations.CreateModel(
            name='PatologiaRicovero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patologia', models.ForeignKey(db_column='codPatologia', on_delete=django.db.models.deletion.CASCADE, to='ricoveri.patologia')),
                ('ricovero', models.ForeignKey(db_column='codRicovero', on_delete=django.db.models.deletion.CASCADE, to='ricoveri.ricovero')),
            ],
            options={
                'unique_together': {('ricovero', 'patologia')},
            },
        ),
    ]
