# Generated by Django 6.0.6 on 2026-06-19 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cittadino',
            fields=[
                ('cssn', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField()),
                ('luogo_nascita', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ospedale',
            fields=[
                ('cod_ospedale', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('citta', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=255)),
                ('dir_sanitario', models.CharField(max_length=16)),
                ('latitudine', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitudine', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('cod_patologia', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('descrizione', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ricovero',
            fields=[
                ('cod_ricovero', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('cittadino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricoveri.cittadino')),
                ('ospedale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricoveri.ospedale')),
                ('patologie', models.ManyToManyField(blank=True, to='ricoveri.patologia')),
            ],
        ),
    ]
